backend:
  name: github
  repo: sofiafrog2004-creator/sonjass_photo
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: simple

site_url: https://sonjass-photo.pages.dev
display_url: https://sonjass-photo.pages.dev


collections:
  - label: "Сайт"
    name: "site"

    files:
      - label: "Основная информация"
        name: "main"
        file: "content/site.json"
        format: json

        fields:

          - label: "Имя / бренд"
            name: "brand"
            widget: "string"

          - label: "Город"
            name: "city"
            widget: "string"

          - label: "Главный заголовок"
            name: "heroTitle"
            widget: "string"

          - label: "Текст"
            name: "heroText"
            widget: "text"

          - label: "Главное фото"
            name: "heroImage"
            widget: "image"

          - label: "Фото обо мне"
            name: "aboutImage"
            widget: "image"

          - label: "Заголовок обо мне"
            name: "aboutTitle"
            widget: "string"

          - label: "Должность"
            name: "aboutRole"
            widget: "string"

          - label: "Описание"
            name: "aboutText"
            widget: "text"

          - label: "Лет в фотографии"
            name: "years"
            widget: "string"

          - label: "Подпись лет"
            name: "yearsLabel"
            widget: "string"

          - label: "Любовь"
            name: "love"
            widget: "string"

          - label: "Подпись любви"
            name: "loveLabel"
            widget: "string"

          - label: "Работы"
            name: "works"
            widget: "list"
            fields:

              - label: "Фото"
                name: "image"
                widget: "image"

              - label: "Категория"
                name: "category"
                widget: "string"

              - label: "Описание"
                name: "alt"
                widget: "string"

          - label: "Отзывы"
            name: "reviews"
            widget: "list"

            fields:

              - label: "Текст"
                name: "text"
                widget: "text"

              - label: "Автор"
                name: "author"
                widget: "string"
